### ISSUE TITLE
标签与分类显示条目不全

### ISSUE THREAD

**Issue by GD2021** [chengzhongxue/halo-theme-fluid#1]
请问标签与分类是不是有显示数量限制
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/81171294/ddb17c80-1ae5-4f5c-9e6a-8894721320a0)

实际有21条，但是只显示了部分

![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/81171294/0ad7097e-858b-48c8-bdc5-6ca601dd149e)

**Comment by w-flac** [comment]
在console的设置里集成显示数量
