### ISSUE TITLE
黑色主题代码部分会看不清

### ISSUE THREAD

**Issue by PeaceEnvoy8** [chengzhongxue/halo-theme-fluid#12]
![2024-06-12_17-36](https://github.com/chengzhongxue/halo-theme-fluid/assets/142609389/16ca7bf7-792a-4a6d-b498-bdcf589e0cd1)

**Comment by PeaceEnvoy8** [comment]
![2024-06-12_17-40](https://github.com/chengzhongxue/halo-theme-fluid/assets/142609389/db773138-ce39-4b88-b7b2-dbd358ac306a)
白色主题是正常的

**Comment by chengzhongxue** [comment]
我服了， 你安装highlight.js 代码高亮：https://halo.run/store/apps/app-sqpgf

**Comment by PeaceEnvoy8** [comment]
> 我服了， 你安装highlight.js 代码高亮：https://halo.run/store/apps/app-sqpgf

这种情况只能通过安装代码高亮解决？我在主页也看到过，但是不确定是否有用，毕竟之前使用原本的主题是不存在这个问题的，黑色主题的时候会自动将代码框内的文字转成白色

**Comment by chengzhongxue** [comment]
你安装了就知道了，有些主题是不一样的
