### ISSUE TITLE
主题很漂亮,发现个问题

### ISSUE THREAD

**Issue by baoyu0** [chengzhongxue/halo-theme-fluid#13]
亲，highlight.js 代码高亮插件已经下载并应用咯，可是呀，块里面代码没有按照语言去高亮显示呢，仅仅是代码块高亮显示了哟。

**Comment by chengzhongxue** [comment]
给个预览地址我看看

**Comment by baoyu0** [comment]
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/128916922/9ca5a26d-aa68-4604-8fc8-43b65bca47d1)
预览图

**Comment by baoyu0** [comment]
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/128916922/85ab6649-16a6-4a94-ac9a-e2e464d6e937)
期待的图

**Comment by baoyu0** [comment]
其实我在打开网页的一瞬间看见是代码高亮的,可是随后就变成白底黑字或者黑底白字了,失去了色彩,是我哪里设置的不对吗?

**Comment by chengzhongxue** [comment]
插件不支持那样，不太想改这快的代码块

**Comment by chengzhongxue** [comment]
建议设置个黑白 通用的颜色的

**Comment by baoyu0** [comment]
![Uploading 1.gif…]()
网页赶紧去是代码高亮的,加载完就是黑白的了

**Comment by baoyu0** [comment]
https://image.baoyu2023.top/file/db98aeca90f5c9d763dca.gif

网页刚加载进去,是代码高亮的,加载完就变成黑白的了

**Comment by baoyu0** [comment]
edge浏览器是黑白的,chrome是彩色的

**Comment by chengzhongxue** [comment]
> edge浏览器是黑白的,chrome是彩色的
dege浏览器没办法

**Comment by baoyu0** [comment]
亲呐，看了一下哈，在 edge 的隐私模式下是可以做到代码高亮显示的哟，换了 halo 的其他主题后呢，有的主题能支持高亮显示，有的却不支持呀，也不晓得这到底是啥状况呀。

**Comment by chengzhongxue** [comment]
https://demo.kunkunyu.com/archives/hello-halo

**Comment by baoyu0** [comment]
```Python
1. num=0
2. for a in range(1,5):
3.     for b in range(1,5):
4.         for c in range(1,5):
5.             if((a!=b)and(a!=c)and(b!=c)):
6.               print(a,b,c)
7.               num+=1
8. print (num)

```

**Comment by baoyu0** [comment]
你给的网址也没代码块啊,看不出效果

**Comment by chengzhongxue** [comment]
算了，你如果还是用的edge浏览器那我就无话可说了，无解

**Comment by baoyu0** [comment]
哇塞！今天我总算搞明白状况啦！原来是我的 Edge 浏览器安装了一个叫做“读点东西”的插件，害得网页加载都不正常啦！不过呢，我把它关闭之后，一切就都好起来喽！说实话呀，我还真不太清楚这个插件得点击才能发挥作用，也不明白为啥，就算没启用竟然也能对页面加载产生影响呢！
