### ISSUE TITLE
提几个小建议

### ISSUE THREAD

**Issue by godcop** [chengzhongxue/halo-theme-fluid#14]
1、建议首页导航栏右侧图标及链接可自定义。使用菜单加链接的方式的话，是必须要带文字才行，并不好使。这个功能可以自定义如登录按钮等。
<img width="478" alt="image" src="https://github.com/chengzhongxue/halo-theme-fluid/assets/18001513/732e19ff-c059-4a44-b09d-c0f9f8edc28f">

2、建议右侧滚动条可选去除，有滚动条的话破坏了首页全屏大图的整体性。
<img width="627" alt="image" src="https://github.com/chengzhongxue/halo-theme-fluid/assets/18001513/401145b4-639b-4860-8cb4-a785a43478cf">

3、建议增加针对全站私有情况下的首页显示逻辑。
<img width="1440" alt="image" src="https://github.com/chengzhongxue/halo-theme-fluid/assets/18001513/e6776e50-0fa9-402f-a5f8-2a2d83281ed9">

4、建议导航栏左侧logo可选自定义图片。

最后，非常感谢作者分享这么优秀的主题，加油！

**Comment by chengzhongxue** [comment]
你这不是挺会改的？欢迎pr

**Comment by godcop** [comment]
> 你这不是挺会改的？欢迎pr

哈哈哈，不太会写java模板，摸索着改了改

**Comment by godcop** [comment]
还有就是文章尾部那个版权信息框内的文章链接，halo系统会识别成本地地址，如果是部署在容器中的话，就会是http://localhost:8090/开头的错误url。所以建议这个不直接用系统的变量，改为可自定义设置域名

**Comment by chengzhongxue** [comment]
> 还有就是文章尾部那个版权信息框内的文章链接，halo系统会识别成本地地址，如果是部署在容器中的话，就会是[http://localhost:8090/开头的错误url。所以建议这个不直接用系统的变量，改为可自定义设置域名](http://localhost:8090/%E5%BC%80%E5%A4%B4%E7%9A%84%E9%94%99%E8%AF%AFurl%E3%80%82%E6%89%80%E4%BB%A5%E5%BB%BA%E8%AE%AE%E8%BF%99%E4%B8%AA%E4%B8%8D%E7%9B%B4%E6%8E%A5%E7%94%A8%E7%B3%BB%E7%BB%9F%E7%9A%84%E5%8F%98%E9%87%8F%EF%BC%8C%E6%94%B9%E4%B8%BA%E5%8F%AF%E8%87%AA%E5%AE%9A%E4%B9%89%E8%AE%BE%E7%BD%AE%E5%9F%9F%E5%90%8D)

这个不太建议手动填写，因为这个如果实在不正确的话其他地方也是有问题的

**Comment by chengzhongxue** [comment]
建议去吧这个系统地址设置正确

**Comment by godcop** [comment]
> 建议去吧这个系统地址设置正确

这几天才开始用halo，在哪里设置系统地址呢？我用1panel面板的容器安装后再反代的

**Comment by chengzhongxue** [comment]
> > 建议去吧这个系统地址设置正确
> 
> 这几天才开始用halo，在哪里设置系统地址呢？我用1panel面板的容器安装后再反代的

![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/89380218/c2b6729c-96cd-4055-ba51-cf95e16a0bf9)

**Comment by godcop** [comment]
> > > 建议去吧这个系统地址设置正确
> > 
> > 
> > 这几天才开始用halo，在哪里设置系统地址呢？我用1panel面板的容器安装后再反代的
> 
> ![image](https://private-user-images.githubusercontent.com/89380218/340767640-c2b6729c-96cd-4055-ba51-cf95e16a0bf9.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg3MzA5MjYsIm5iZiI6MTcxODczMDYyNiwicGF0aCI6Ii84OTM4MDIxOC8zNDA3Njc2NDAtYzJiNjcyOWMtOTZjZC00MDU1LWJhNTEtY2Y5NWUxNmEwYmY5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE4VDE3MTAyNlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTJhZWEzMzhkZjhiYmFiZjYxNDZmYzI0NGE3MzMwYjg1YzNkOTUxMzEzMjdkOGQyYTJjZDk3MDA4Yjg0ZTRhOWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.ijD4RMFS77msxXp5oKJZjq5-aMd5OSF5-sfqN0qIVt8)

哦哦，好的，谢谢

**Comment by chengzhongxue** [comment]
目前可能不会去修改当前提出的建议

**Comment by godcop** [comment]
> 目前可能不会去修改当前提出的建议

我加了一些新的功能，修了一下原来存在bug的部分，提PR了，看有没有必要合并

**Comment by chengzhongxue** [comment]
> > 目前可能不会去修改当前提出的建议
> 
> 我加了一些新的功能，修了一下原来存在bug的部分，提PR了，看有没有必要合并

有兴趣可以加适配下图库页面和瞬间页面

**Comment by godcop** [comment]
> > > 目前可能不会去修改当前提出的建议
> > 
> > 
> > 我加了一些新的功能，修了一下原来存在bug的部分，提PR了，看有没有必要合并
> 
> 有兴趣可以加适配下图库页面和瞬间页面

不太会用那个图库和瞬间，我还有几个想到的功能没加上去

**Comment by chengzhongxue** [comment]
> > > > 目前可能不会去修改当前提出的建议
> > > 
> > > 
> > > 我加了一些新的功能，修了一下原来存在bug的部分，提PR了，看有没有必要合并
> > 
> > 
> > 有兴趣可以加适配下图库页面和瞬间页面
> 
> 不太会用那个图库和瞬间，我还有几个想到的功能没加上去

加吧，看看合适不

**Comment by chengzhongxue** [comment]
等会，你加啥了，怎么主题包变成16mb了，吓我一跳

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/89380218/0d26e759-4e6e-4e9a-abf9-fcdc8461ff75)
我去你要玩死我啊，这几个文件15mb不能这样玩啊大兄弟

**Comment by chengzhongxue** [comment]
你进一下那个微信群吧，可以在群里沟通
