### ISSUE TITLE
关于暗黑模式下代码颜色的问题

### ISSUE THREAD

**Issue by hunxuankai** [chengzhongxue/halo-theme-fluid#3]
如图，网页暗黑模式的时候，代码竟然还是黑色的
能否让代码高亮显示？
![PixPin_2024-05-01_21-48-48](https://github.com/chengzhongxue/halo-theme-fluid/assets/37786366/5b4b7169-a85c-468a-949a-57bbddef8b99)

**Comment by CieanYau** [comment]
你好，复现了一下你的问题，这个解决方法请在
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/89917804/a28bedec-a72c-408c-a335-9bf7752b9b30)
下面配置
/archives/**

**Comment by Nipuru** [comment]
分隔线和表格边线的颜色 (暗色模式)也不起作用

**Comment by chengzhongxue** [comment]
1.0.3版本修复
