### ISSUE TITLE
主题不会对引用内容做出区分

### ISSUE THREAD

**Issue by QingFeng-awa** [chengzhongxue/halo-theme-fluid#4]
## 系统信息
- 外部访问地址: https://qingfengawa.me
- 启动时间: 2024-05-03 19:09
- 版本: 2.15.0
- 构建时间: 2024-04-30 16:27
- Git Commit: 1582a62
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: MySQL Community Server - GPL / 8.2.0
- 操作系统: Linux / 5.15.0-105-generic
- 已激活主题: [Theme Fluid](https://github.com/chengzhongxue/halo-theme-fluid)
- 已启动插件:
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [站点推送插件](https://github.com/Stonewuu/halo-plugin-sitepush)
  - [KaTeX](https://github.com/halo-sigs/plugin-katex)
  - [文章导入导出](https://jhacker.cn/2023/halo-plugin-export2doc)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [OAuth2 认证](https://github.com/halo-sigs/plugin-oauth2)
  - [Meilisearch](https://github.com/Rainsheep/halo-plugin-meilisearch)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [Markdown / HTML 内容块](https://github.com/halo-dev/plugin-hybrid-edit-block)
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Sitemap](https://github.com/halo-dev/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)

## 主要问题
问题主要描述如标题。
问题示例请见上传的图片。
这是我们在默认编辑器中看到的效果:
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/151742581/df85c5ad-195b-4a5a-8316-c71960b25016)
但预览与实际发布看到的效果却是这样的:
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/151742581/af1f74dc-6e78-4146-a254-2c8bb56e5496)
## 主题配置
我没有在`/console/theme/settings/color`中找到有关配置引用内容的相关设置。

**Comment by chengzhongxue** [comment]
我看看，下个版本适配吧

**Comment by chengzhongxue** [comment]
这个是正常的
