### ISSUE TITLE
求做个悬浮音乐播放插件

### ISSUE THREAD

**Issue by shanpf** [chengzhongxue/halo-theme-fluid#5]
我用代码注入做会随页面刷新重新加载音乐播放插件

**Comment by chengzhongxue** [comment]
在主题做也会这样，因为主题没有适配 pjax 要适配这个只能行

**Comment by shanpf** [comment]
@chengzhongxue 已经解决了，解决方法如下：
扩展设置：
头部
`<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
  <script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js"></script>`
  底部
  `<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
<script type='text/javascript' src='https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js'></script>

<div id='meting-div'>
<meting-js 
  server="netease" 
  type="playlist" 
  id="#id"
  fixed="true" 
  autoplay="false"
  loop="all"
  order="list"
  preload="auto"
  list-folded="ture"
  list-max-height="500px"
  lrc-type="1">
</meting-js>
</div>

<script src="https://cdn.jsdelivr.net/npm/pjax/pjax.js"></script>
<script>
	var pjax = new Pjax({
  selectors: [
    "div[id=banner]",
    "main"
  ],
  cacheBust: false
})
</script>`

**Comment by shanpf** [comment]
好，打字机效果没了

**Comment by shanpf** [comment]
问题挺大的我再看看

**Comment by shanpf** [comment]
最终方案：
扩展设置：
头部
`<script>(function (window,document) {var typing =Fluid.plugins.typing;var subtitle =document.getElementById('subtitle');if (!subtitle ||!typing) {return;}
var text =subtitle.getAttribute('data-typed-text');var urlinfo =window.location.pathname;urlinfo =decodeURIComponent(urlinfo);if (false &&urlinfo =='/') {$.ajax({type:"GET",url:'https://v1.hitokoto.cn/',success:function(result) {var apiText;if (result) {var keysData ='hitokoto';var keys =keysData.split(',');if (result instanceof Array) {result =result[0];}
for (const k of keys) {var value =result[k];if (typeof value ==='string') {apiText =value;break;} else if (value instanceof Object) {result =value;}
}
}
apiText ?typing(apiText) :typing(text);},error:function(xhr,status,error) {if (error) {var url ='https://v1.hitokoto.cn/'
console.error(`Failed to request ${url}:`,error);}
typing(text);}
})
}else {typing(text);}
})(window,document);</script>`
底部
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.css">
  <script src="https://cdn.jsdelivr.net/npm/aplayer/dist/APlayer.min.js"></script>
  
  <script src="https://cdn.jsdelivr.net/npm/meting@2.0.1/dist/Meting.min.js"></script>
<script src="https://code.jquery.com/jquery-3.0.0.min.js"></script>
<script type='text/javascript' src='https://cdn.bootcss.com/jquery.pjax/2.0.1/jquery.pjax.min.js'></script>

<meting-js 
  server="netease" 
  type="playlist" 
  id="10053679048"
  fixed="true" 
  autoplay="false"
  loop="all"
  order="list"
  preload="auto"
  list-folded="ture"
  list-max-height="500px"
  lrc-type="1">
</meting-js>

<script src="https://cdn.jsdelivr.net/npm/pjax/pjax.js"></script>
<script>
	var pjax = new Pjax({
  // 在页面进行 PJAX 时需要被替换的元素或容器，一条一个 CSS 选择器，数组形式
  selectors: [
    "head",
    "div[id=banner]",
    "main"
  ],
  cacheBust: false
})
</script>
