### ISSUE TITLE
前端渲染代码块类型貌似所有都是TEXT类型

### ISSUE THREAD

**Issue by zyy2477** [chengzhongxue/halo-theme-fluid#6]
- 外部访问地址: https://www.seafog.cn/
- 启动时间: 2024-05-22 08:26
- 版本: 2.15.2
- 构建时间: 2024-05-10 14:17
- Git Commit: 9a4c41a
- Java: IBM Semeru Runtime Open Edition / 21.0.2+13-LTS
- 数据库: Source distribution / 8.0.34
- 操作系统: Linux / 4.18.0-477.13.1.el8_8.x86_64
- 已激活主题: [Theme Fluid](https://github.com/chengzhongxue/halo-theme-fluid)
- 已启动插件:
  - [lightgallery.js 灯箱](https://github.com/halo-sigs/plugin-lightgallery)
  - [Vditor 编辑器](https://github.com/justice2001/halo-plugin-vditor)
  - [应用市场](https://www.halo.run/store/apps/app-VYJbF)
  - [highlight.js 代码高亮](https://github.com/halo-sigs/plugin-highlightjs)
  - [对象存储（Amazon S3 协议）](https://github.com/halo-dev/plugin-s3)
  - [图库管理](https://github.com/halo-sigs/plugin-photos)
  - [瞬间](https://github.com/halo-sigs/plugin-moments)
  - [链接管理](https://github.com/halo-sigs/plugin-links)
  - [ByteMD](https://github.com/ruibaby/plugin-bytemd)
  - [Sitemap](https://github.com/halo-sigs/plugin-sitemap)
  - [搜索组件](https://github.com/halo-dev/plugin-search-widget)
  - [RSS](https://github.com/halo-sigs/plugin-feed)
  - [评论组件](https://github.com/halo-dev/plugin-comment-widget)

## 问题
在markdown中已标明代码块类型为python：
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/23225911/ade4cde3-9fc1-451d-86f6-9b4f30593231)

前端渲染中貌似所有都是TEXT类型：

![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/23225911/96b891d1-545c-4d25-ba30-b55f2c797313)

**Comment by chengzhongxue** [comment]
下个版本会去掉这个

**Comment by Nipuru** [comment]
加油

> 下个版本会去掉这个

**Comment by chengzhongxue** [comment]
版本更新 1.0.3 取消了这个
