### ISSUE TITLE
代码块样式丢失问题

### ISSUE THREAD

**Issue by Nipuru** [chengzhongxue/halo-theme-fluid#8]
如图 在此次更新之后代码块样式直接没了

![截图](https://github.com/chengzhongxue/halo-theme-fluid/assets/36749609/9f2c4fa8-2052-4ce5-a272-8ab5adfc9d05)

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/89380218/30cced7e-c8bb-44b4-85eb-7b1f6d8c6526)
不知道说什么好

**Comment by chengzhongxue** [comment]
![image](https://github.com/chengzhongxue/halo-theme-fluid/assets/89380218/4cc42591-8e4c-43d9-8042-8a7df59945fa)
